# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg', '0002_auto_20160923_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pokes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poke_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poke_sources', to='login_reg.User')),
                ('poke_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poke_targets', to='login_reg.User')),
            ],
        ),
    ]
